version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: badger
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
networks:
  evermos_net:
    driver: bridge
volumes:
  my-db:
